#+TITLE: MMAP
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://klose911.github.io/html/material/css/main.css" />
#+OPTIONS: num:nil timestamp:nil ^:nil

The _mmap_ and munmap system calls allow UNIX programs to exert detailed *control over* their _address spaces_ . They can be used to
+ share memory among processes
+ to map files into process address spaces
+ as part of user-level page fault schemes such as the garbage-collection algorithms discussed in lecture

#+begin_example
  In this lab you'll add mmap and munmap to xv6, focusing on memory-mapped files
#+end_example

* mmap 
The manual page (run _man 2 mmap_ ) shows this declaration for mmap:

#+begin_src c 
  void *mmap(void *addr, size_t len, int prot, int flags,
             int fd, off_t offset);
#+end_src

mmap can be called in many ways, but this lab requires only a subset of its features relevant to *memory-mapping a file* . You can assume that
+ _addr_ will *always be zero* , meaning that the kernel should decide the virtual address at which to map the file
+ mmap returns that address, or _0xffffffffffffffff_ if it fails
+ len is _the number of bytes to map_ ; it might not be the same as the file's length
+ prot indicates whether the memory should be mapped readable, writeable, and/or executable
  + you can assume that prot is _PROT_READ_ or _PROT_WRITE_ or _both_
+ flags will be either
  + _MAP_SHARED_  meaning that modifications to the mapped memory should be written back to the file
  + _MAP_PRIVATE_  meaning that they should not
    #+begin_example
      You don't have to implement any other bits in flags
    #+end_example
+ fd is the _open file descriptor_ of the file to map
+ You can assume *offset is zero* (it's the starting point in the file at which to map)

Your implementation should _fill in the page table_ *lazily* , in response to *page faults* . That is, mmap itself *should not allocate* physical memory or read the file. Instead, do that in _page fault handling_ code in (or called by) usertrap, as in the copy-on-write lab

#+begin_example
  The reason to be lazy is to ensure that mmap of a large file is fast

  and that mmap of a file larger than physical memory is possible
#+end_example

It's OK if processes that map the same MAP_SHARED file do not share physical pages.

* munmap 
The manual page (run _man 2 munmap_ ) shows this declaration for munmap:

#+begin_src c 
  int munmap(void *addr, size_t len);
#+end_src

munmap should *remove* _mmap mappings_ in the indicated address range if any
+ If the process has modified the memory and has it mapped MAP_SHARED, the modifications should first be written to the file
+ An munmap call might cover only _a portion_ of an mmap-ed region, but you can assume that it will either unmap _at the start_ , or  _at the end_ , or _the whole region_
  #+begin_example
    but not punch a hole in the middle of a region
  #+end_example
+ When a process _exits_ , any modifictions it has made to MAP_SHARED regions should be written to the relevant files, as if the process had called munmap

* Job
#+begin_example
  You should implement enough mmap and munmap functionality to make the mmaptest test program work

  If mmaptest doesn't use a mmap feature, you don't need to implement that feature

  You must also ensure that usertests -q continues to work
#+end_example

When you're done, you should see output similar to this:

#+begin_src sh 
  $ mmaptest
  test basic mmap
  test basic mmap: OK
  test mmap private
  test mmap private: OK
  test mmap read-only
  test mmap read-only: OK
  test mmap read/write
  test mmap read/write: OK
  test mmap dirty
  test mmap dirty: OK
  test not-mapped unmap
  test not-mapped unmap: OK
  test lazy access
  test lazy access: OK
  test mmap two files
  test mmap two files: OK
  test fork
  test fork: OK
  test munmap prevents access
  usertrap(): unexpected scause 0xd pid=7
  sepc=0x924 stval=0xc0001000
  usertrap(): unexpected scause 0xd pid=8
  sepc=0x9ac stval=0xc0000000
  test munmap prevents access: OK
  test writes to read-only mapped memory
  usertrap(): unexpected scause 0xf pid=9
  sepc=0xaf4 stval=0xc0000000
  test writes to read-only mapped memory: OK
  mmaptest: all tests succeeded
  $ usertests -q
  usertests starting
  ...
  ALL TESTS PASSED
  $ 
#+end_src

** Hints
1. Start by adding *_mmaptest* to _UPROGS_ , and _mmap_ and _munmap_ system calls, in order to get user/mmaptest.c to compile
   + For now, just return errors from mmap and munmap
   + We defined *PROT_READ* etc for you in _kernel/fcntl.h_
   + Run mmaptest, which will fail at the first mmap call
2. Keep track of what mmap has mapped for each process
   + *Define* a _structure_ corresponding to the *VMA* _virtual memory area_ described in the "virtual memory for applications" lecture. This should record
     + the _address_ , _length_ ,  _permissions_ ,  _file_ , etc. for a virtual memory range created by mmap
     + Since the xv6 kernel doesn't have a variable-size memory allocator in the kernel, it's OK to declare a _fixed-size array_ of VMAs and allocate from that array as needed
       #+begin_example
	 A size of 16 should be sufficient
       #+end_example
3. Implement mmap:
   1. find an *unused region* in the process's address space in which to map the file
   2. add a VMA to the process's table of mapped regions
      + The VMA should contain a pointer to a struct file for the file being mapped
      + mmap should increase the file's reference count so that the structure doesn't disappear when the file is closed (hint: see _filedup_)
   3. Run mmaptest: the first mmap should succeed, but the first access to the mmap-ed memory will cause a page fault and kill mmaptest
4. Add code to cause a page-fault in a mmap-ed region to
   + *allocate* a page of physical memory
   + read 4096 bytes of the relevant file into that page
     + . Read the file with readi, which takes an offset argument at which to read in the file (but you will have to lock/unlock the inode passed to readi)
   + map it into the user address space
   + Don't forget to set the permissions correctly on the page
   + Run mmaptest; it should get to the first munmap
5. Implement munmap:
   1. find the VMA for the address range and unmap the specified pages (hint: use _uvmunmap_ )
   2. If munmap removes all pages of a previous mmap, it should *decrement* the reference count of the corresponding struct file
   3. If an unmapped page has been modified and the file is mapped MAP_SHARED, *write* the page back to the file
      + Look at _filewrite_ for inspiration
6. Ideally your implementation would only write back *MAP_SHARED* pages that the program actually modified
   + The _dirty bit_ (D) in the _RISC-V PTE_ indicates whether a page has been written
   + However, mmaptest does not check that non-dirty pages are not written back
     #+begin_example
       thus you can get away with writing pages back without looking at D bits
     #+end_example
7. Modify _exit_ to *unmap* the process's mapped regions as if munmap had been called
   + Run mmaptest; all tests through test mmap two files should pass, but probably not test fork
8. Modify _fork_ to ensure that the child has the *same* _mapped regions_ as the parent
   + Don't forget to *increment* the reference count for a VMA's struct file
   + In the page fault handler of the child, it is OK to allocate a new physical page instead of sharing a page with the parent
     #+begin_example
       The latter would be cooler, but it would require more implementation work
     #+end_example
   + Run mmaptest; it should pass all the tests

#+begin_example
Run usertests -q to make sure everything still works
#+end_example
